name: Trigger auto deployment for ref3-goal-achievement-adviser

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "app/**"
      - ".github/workflows/ref3-goal-achievement-adviser-AutoDeployTrigger-8495216e-2590-4eb1-968f-ba7cdeec5ee7.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Create and populate .env file
        env:
          AZURE_OPENAI_SERVICE: ${{ secrets.AZURE_OPENAI_SERVICE }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_CHAT_MODEL: ${{ secrets.AZURE_OPENAI_CHAT_MODEL }}
          AZURE_OPENAI_CHAT_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }}
          AZURE_OPENAI_EMBEDDING_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT }}
          REDIS_NAME: ${{ secrets.REDIS_NAME }}
          REDIS_KEY: ${{ secrets.REDIS_KEY }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: |
          touch .env
          echo AZURE_OPENAI_SERVICE="$AZURE_OPENAI_SERVICE" >> .env
          echo AZURE_OPENAI_KEY="$AZURE_OPENAI_KEY" >> .env
          echo AZURE_OPENAI_API_VERSION="2023-07-01-preview" >> .env
          echo AZURE_OPENAI_CHAT_MODEL="$AZURE_OPENAI_CHAT_MODEL" >> .env
          echo AZURE_OPENAI_CHAT_DEPLOYMENT="$AZURE_OPENAI_CHAT_DEPLOYMENT" >> .env
          echo AZURE_OPENAI_EMBEDDING_DEPLOYMENT="$AZURE_OPENAI_EMBEDDING_DEPLOYMENT" >> .env
          echo REDIS_NAME="$REDIS_NAME" >> .env
          echo REDIS_KEY="$REDIS_KEY" >> .env
          echo REDIS_INDEX_CATEGORY="task-planning" >> .env
          echo REDIS_INDEX_NAME="embedding_index" >> .env
          echo AZURE_STORAGE_CONNECTION_STRING="$AZURE_STORAGE_CONNECTION_STRING" >> .env
          echo AZURE_STORAGE_ACCOUNT="$AZURE_STORAGE_ACCOUNT" >> .env
          echo AZURE_STORAGE_KEY="$AZURE_STORAGE_KEY" >> .env
          echo AZURE_STORAGE_CONTAINER="$AZURE_STORAGE_CONTAINER" >> .env
          echo BASIC_AUTH_USER="$BASIC_AUTH_USER" >> .env
          echo BASIC_AUTH_PASSWORD="$BASIC_AUTH_PASSWORD" >> .env

          echo "cat .env"
          cat .env

          echo "ls -a ."
          ls -a .

          echo "Move .env file to backend folder"
          mv .env app/backend/

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REF3GOALACHIEVEMENTADVISER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REF3GOALACHIEVEMENTADVISER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REF3GOALACHIEVEMENTADVISER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/app
          registryUrl: swoaidemoregistry.azurecr.io
          registryUsername: ${{ secrets.REF3GOALACHIEVEMENTADVISER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REF3GOALACHIEVEMENTADVISER_REGISTRY_PASSWORD }}
          containerAppName: ref3-goal-achievement-adviser
          resourceGroup: aoai_refer_art_rg
          imageToBuild: swoaidemoregistry.azurecr.io/ref3-goal-achievement-adviser:${{ github.sha }}
          dockerfilePath: Dockerfile
          # environmentVariables: AZURE_OPENAI_SERVICE=${{ secrets.AZURE_OPENAI_SERVICE }} AZURE_OPENAI_KEY=${{ secrets.AZURE_OPENAI_KEY }} AZURE_OPENAI_CHAT_MODEL=${{ secrets.AZURE_OPENAI_CHAT_MODEL }} AZURE_OPENAI_CHAT_DEPLOYMENT=${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }} REDIS_NAME=${{ secrets.REDIS_NAME }} AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT }} AZURE_STORAGE_KEY=${{ secrets.AZURE_STORAGE_KEY }} AZURE_STORAGE_CONTAINER=${{ secrets.AZURE_STORAGE_CONTAINER }} BASIC_AUTH_USER=${{ secrets.BASIC_AUTH_USER }} BASIC_AUTH_PASSWORD=${{ secrets.BASIC_AUTH_PASSWORD }}
